/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/components/appearance/themes/kids-sprout.ts
 * Command: astryx theme build src/components/appearance/themes/kids-sprout.ts
 * CLI: @astryxdesign/cli@0.6.0
 * Core: @astryxdesign/core@0.6.0
 */

/**
 * kids-sprout theme — built by `pnpm exec astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { kidsSproutTheme } from './kids-sprout';
 *   import './kids-sprout.css';
 */
export const kidsSproutTheme = {
  name: 'kids-sprout',
  __built: true,
  tokens: {
    "--font-size-4xs": "0.4375rem",
    "--font-size-3xs": "0.5rem",
    "--font-size-2xs": "0.625rem",
    "--font-size-xs": "0.8125rem",
    "--font-size-sm": "1rem",
    "--font-size-base": "1.25rem",
    "--font-size-lg": "1.5625rem",
    "--font-size-xl": "1.9375rem",
    "--font-size-2xl": "2.375rem",
    "--font-size-3xl": "2.9375rem",
    "--font-size-4xl": "3.6875rem",
    "--font-size-5xl": "4.5625rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-bold)",
    "--text-heading-1-leading": "1.2632",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-bold)",
    "--text-heading-2-leading": "1.4194",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-bold)",
    "--text-heading-3-leading": "1.44",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-bold)",
    "--text-heading-4-leading": "1.4",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-bold)",
    "--text-heading-5-leading": "1.5",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-bold)",
    "--text-heading-6-leading": "1.5385",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-medium)",
    "--text-body-leading": "1.4",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.44",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.4",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.4",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.5",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.2603",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.2203",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.2766",
    "--duration-fast-min": "160ms",
    "--duration-fast": "200ms",
    "--duration-fast-max": "250ms",
    "--duration-medium-min": "270ms",
    "--duration-medium": "340ms",
    "--duration-medium-max": "425ms",
    "--duration-slow-min": "495ms",
    "--duration-slow": "620ms",
    "--duration-slow-max": "775ms",
    "--font-family-body": "\"Nunito Variable\", Nunito Variable, \"Noto Sans SC Variable\", \"PingFang SC\", \"Hiragino Sans GB\", \"Microsoft YaHei\", sans-serif",
    "--font-family-heading": "\"Nunito Variable\", Nunito Variable, \"Noto Sans SC Variable\", \"PingFang SC\", \"Hiragino Sans GB\", \"Microsoft YaHei\", sans-serif",
    "--font-family-code": "ui-monospace, \"SF Mono\", Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
    "--color-syntax-keyword": "light-dark(#6b187c, #efa8ff)",
    "--color-syntax-string": "light-dark(#0b5615, #a4d6a3)",
    "--color-syntax-comment": "light-dark(#6a6a6a, #9e9e9e)",
    "--color-syntax-number": "light-dark(#733100, #ffb37e)",
    "--color-syntax-function": "light-dark(#00458c, #a1caff)",
    "--color-syntax-type": "light-dark(#6b187c, #efa8ff)",
    "--color-syntax-variable": "light-dark(#111111, #e2e2e2)",
    "--color-syntax-operator": "light-dark(#6a6a6a, #9e9e9e)",
    "--color-syntax-constant": "light-dark(#733100, #ffb37e)",
    "--color-syntax-tag": "light-dark(#8a0011, #ffaea7)",
    "--color-syntax-attribute": "light-dark(#584400, #eec448)",
    "--color-syntax-property": "light-dark(#005348, #90d7c8)",
    "--color-syntax-punctuation": "light-dark(#6a6a6a, #9e9e9e)",
    "--color-syntax-background": "light-dark(#ffffff, #111111)",
    "--color-background-surface": "light-dark(#FFFDF8, #332E27)",
    "--color-background-body": "light-dark(#FFF8E8, #29241E)",
    "--color-background-card": "light-dark(#FFF6D8, #3A342B)",
    "--color-background-popover": "light-dark(#FFFDF8, #40392F)",
    "--color-background-muted": "light-dark(#F7ECCF, #453E34)",
    "--color-accent": "light-dark(#1F7A68, #7BE0C1)",
    "--color-accent-muted": "light-dark(#D9F3EC, #7BE0C133)",
    "--color-neutral": "light-dark(#101E1B1A, #D5E6E033)",
    "--color-overlay": "light-dark(#101E1B66, #111E1A99)",
    "--color-overlay-hover": "light-dark(#101E1B0D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#101E1B1A, #FFFFFF1A)",
    "--color-text-primary": "light-dark(#3E3428, #FFF3D6)",
    "--color-text-secondary": "light-dark(#766958, #D8C7A8)",
    "--color-text-disabled": "light-dark(#A19480, #8A7E69)",
    "--color-text-accent": "light-dark(#185C4F, #A7F3D0)",
    "--color-on-dark": "#ffffff",
    "--color-on-light": "#111111",
    "--color-on-accent": "light-dark(#FFFFFF, #15352F)",
    "--color-on-success": "light-dark(#FFFFFF, #17341D)",
    "--color-on-error": "light-dark(#FFFFFF, #3D1210)",
    "--color-on-warning": "light-dark(#FFFFFF, #3E2D00)",
    "--color-icon-accent": "light-dark(#1F7A68, #7BE0C1)",
    "--color-icon-primary": "light-dark(#3E3428, #FFF3D6)",
    "--color-icon-secondary": "light-dark(#766958, #D8C7A8)",
    "--color-icon-disabled": "light-dark(#A19480, #8A7E69)",
    "--color-success": "light-dark(#357A43, #8ED98E)",
    "--color-error": "light-dark(#B7433D, #FF8A84)",
    "--color-warning": "light-dark(#8C5200, #FFD166)",
    "--color-success-muted": "light-dark(#DFF3DC, #8ED98E33)",
    "--color-error-muted": "light-dark(#FBE0DD, #FF8A8433)",
    "--color-warning-muted": "light-dark(#FFF0C2, #FFD16633)",
    "--color-border": "light-dark(#E6D5B5, #5A5042)",
    "--color-border-emphasized": "light-dark(#C9B58A, #796C55)",
    "--color-skeleton": "light-dark(#E8DCC8, #51483C)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--color-background-red": "light-dark(#FBE0DD, #6A302D)",
    "--color-border-red": "light-dark(#C84B45, #FF9C96)",
    "--color-icon-red": "light-dark(#B7433D, #FFB4AF)",
    "--color-text-red": "light-dark(#772D29, #FFD0CC)",
    "--color-background-orange": "light-dark(#ffc7a1, #503424)",
    "--color-border-orange": "light-dark(#ffc7a1, #df843f)",
    "--color-icon-orange": "light-dark(#622700, #ff9e55)",
    "--color-text-orange": "light-dark(#622700, #ffb37e)",
    "--color-background-yellow": "light-dark(#FFF0C2, #6B5315)",
    "--color-border-yellow": "light-dark(#E3A008, #FFD166)",
    "--color-icon-yellow": "light-dark(#B66A00, #FFE29A)",
    "--color-text-yellow": "light-dark(#704700, #FFF0B8)",
    "--color-background-green": "light-dark(#DDF3D8, #315A38)",
    "--color-border-green": "light-dark(#6FBE44, #9CDD87)",
    "--color-icon-green": "light-dark(#3E8E4C, #A6E39A)",
    "--color-text-green": "light-dark(#2E6938, #CBF4C5)",
    "--color-background-teal": "light-dark(#a9e2d6, #28413c)",
    "--color-border-teal": "light-dark(#90d7c8, #4fb1a0)",
    "--color-icon-teal": "light-dark(#00463d, #81c9bb)",
    "--color-text-teal": "light-dark(#00463d, #90d7c8)",
    "--color-background-cyan": "light-dark(#9ae2f4, #274046)",
    "--color-border-cyan": "light-dark(#85d5e9, #49adc4)",
    "--color-icon-cyan": "light-dark(#004351, #71c7dd)",
    "--color-text-cyan": "light-dark(#004351, #85d5e9)",
    "--color-background-blue": "light-dark(#DDEFFD, #31506B)",
    "--color-border-blue": "light-dark(#5FA8FF, #8CC8FF)",
    "--color-icon-blue": "light-dark(#2D6FA8, #9DD3FF)",
    "--color-text-blue": "light-dark(#1D527D, #BDDFFF)",
    "--color-background-purple": "light-dark(#f7d5ff, #4a2f51)",
    "--color-border-purple": "light-dark(#f3bfff, #d885eb)",
    "--color-icon-purple": "light-dark(#5c0e6c, #e496f6)",
    "--color-text-purple": "light-dark(#5c0e6c, #eaacf8)",
    "--color-background-pink": "light-dark(#ffc0d7, #572b3d)",
    "--color-border-pink": "light-dark(#ffc0d7, #fc78b1)",
    "--color-icon-pink": "light-dark(#70003f, #fd92bd)",
    "--color-text-pink": "light-dark(#70003f, #ffa9ca)",
    "--color-background-gray": "light-dark(#e2e2e2, #303030)",
    "--color-border-gray": "light-dark(#d4d4d4, #262626)",
    "--color-icon-gray": "light-dark(#474747, #9e9e9e)",
    "--color-text-gray": "light-dark(#1b1b1b, #d4d4d4)",
    "--radius-none": "0px",
    "--radius-inner": "12px",
    "--radius-element": "16px",
    "--radius-container": "24px",
    "--radius-page": "36px",
    "--radius-full": "9999px",
    "--shadow-low": "0 2px 0 rgba(92, 65, 37, 0.10), 0 4px 12px rgba(92, 65, 37, 0.08)",
    "--shadow-med": "0 4px 0 rgba(92, 65, 37, 0.10), 0 10px 24px rgba(92, 65, 37, 0.12)",
    "--shadow-high": "0 8px 0 rgba(92, 65, 37, 0.10), 0 20px 40px rgba(92, 65, 37, 0.16)",
    "--shadow-inset-hover": "inset 0px 0px 0px 2px #0074e24D",
    "--shadow-inset-selected": "inset 0px 0px 0px 2px #0074e280",
    "--shadow-inset-success": "inset 0px 0px 0px 2px #2f7d334D",
    "--shadow-inset-warning": "inset 0px 0px 0px 2px #f8d36a4D",
    "--shadow-inset-error": "inset 0px 0px 0px 2px #de47454D",
    "--color-background-inverted": "light-dark(#3E3428, #FFF3D6)",
    "--color-track": "light-dark(#D9C9AA, #5A5042)",
    "--color-background-error-inverted": "light-dark(#772D29, #FFD0CC)",
    "--radius-chat": "32px",
    "--border-width": "2px",
    "--focus-outline-width": "4px",
    "--focus-outline-offset": "3px",
    "--focus-outline-color": "#F5B82E",
    "--ease-standard": "cubic-bezier(0.4, 0, 0.2, 1)",
    "--size-element-sm": "40px",
    "--size-element-md": "56px",
    "--size-element-lg": "64px"
  },
  localTokens: {
    "--astryx-theme-neutral-color-status-fill-accent": "light-dark(#0074e2, #6d9cfe)",
    "--astryx-theme-neutral-color-status-fill-success": "light-dark(#198100, #64af4c)",
    "--astryx-theme-neutral-color-status-fill-warning": "#ffce2f",
    "--astryx-theme-neutral-color-status-fill-error": "light-dark(#c9303a, #ff705d)",
    "--astryx-theme-neutral-color-status-muted-accent": "light-dark(#b9d7ff, #88bcff3D)",
    "--astryx-theme-neutral-color-on-tint-neutral": "light-dark(#fafafa4D, #0a0a0a4D)",
    "--astryx-theme-neutral-color-on-tint-overlay-hover": "light-dark(#fafafa1A, #0a0a0a1A)",
    "--astryx-theme-neutral-color-on-tint-overlay-pressed": "light-dark(#fafafa33, #0a0a0a33)",
    "--astryx-theme-neutral-color-destructive-overlay-hover": "light-dark(#ff7f770D, #ee736c0D)",
    "--astryx-theme-neutral-color-destructive-overlay-pressed": "light-dark(#ff7f771A, #ee736c1A)"
  },
  __localTokenOwners: {
    "--astryx-theme-neutral-color-status-fill-accent": "neutral",
    "--astryx-theme-neutral-color-status-fill-success": "neutral",
    "--astryx-theme-neutral-color-status-fill-warning": "neutral",
    "--astryx-theme-neutral-color-status-fill-error": "neutral",
    "--astryx-theme-neutral-color-status-muted-accent": "neutral",
    "--astryx-theme-neutral-color-on-tint-neutral": "neutral",
    "--astryx-theme-neutral-color-on-tint-overlay-hover": "neutral",
    "--astryx-theme-neutral-color-on-tint-overlay-pressed": "neutral",
    "--astryx-theme-neutral-color-destructive-overlay-hover": "neutral",
    "--astryx-theme-neutral-color-destructive-overlay-pressed": "neutral"
  },
  __localTokenLineage: ["neutral","kids-base","kids-sprout"],
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "variant:destructive": {
        "backgroundColor": "var(--color-error)",
        "color": "var(--color-on-error)",
        "--color-overlay-hover": "var(--astryx-theme-neutral-color-destructive-overlay-hover)",
        "--color-overlay-pressed": "var(--astryx-theme-neutral-color-destructive-overlay-pressed)",
        "borderColor": "var(--color-error)",
        "boxShadow": "0 5px 0 0 var(--color-border-emphasized)",
        ":hover": {
          "backgroundColor": "color-mix(in srgb, var(--color-error) 86%, white)",
          "borderColor": "color-mix(in srgb, var(--color-error) 86%, white)",
          "boxShadow": "0 6px 0 0 var(--color-border-emphasized)",
          "transform": "translateY(-1px)"
        },
        ":active": {
          "backgroundColor": "color-mix(in srgb, var(--color-error) 82%, black)",
          "borderColor": "color-mix(in srgb, var(--color-error) 82%, black)",
          "boxShadow": "0 1px 0 0 var(--color-border-emphasized)",
          "transform": "translateY(2px)"
        }
      },
      "base": {
        "borderWidth": "2px",
        "fontWeight": "600",
        "letterSpacing": "0.02em",
        "lineHeight": "1",
        "transitionProperty": "transform, box-shadow, background-color, border-color, color",
        "transitionDuration": "var(--duration-fast)",
        "transitionTimingFunction": "var(--ease-standard)",
        "minHeight": "56px",
        "paddingInline": "24px"
      },
      "size:sm": {
        "borderRadius": "16px",
        "minHeight": "32px",
        "paddingInline": "16px"
      },
      "size:md": {
        "borderRadius": "var(--radius-full)",
        "minHeight": "45px",
        "paddingInline": "20px"
      },
      "size:lg": {
        "borderRadius": "24px",
        "minHeight": "48px",
        "paddingInline": "32px"
      },
      "variant:primary": {
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-background-surface)",
        "color": "var(--color-text-primary)",
        "boxShadow": "0 5px 0 0 var(--color-border-emphasized)",
        ":hover": {
          "backgroundColor": "var(--color-background-surface)",
          "borderColor": "var(--color-background-surface)",
          "boxShadow": "0 6px 0 0 var(--color-border-emphasized)",
          "transform": "translateY(-1px)"
        },
        ":active": {
          "backgroundColor": "var(--color-background-surface)",
          "borderColor": "var(--color-background-surface)",
          "boxShadow": "0 1px 0 0 var(--color-border-emphasized)",
          "transform": "translateY(2px)"
        },
        ":focus-visible": {
          "outline": "var(--focus-outline-width) solid var(--focus-outline-color)",
          "outlineOffset": "var(--focus-outline-offset)"
        }
      },
      "variant:secondary": {
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border)",
        "color": "var(--color-text-primary)",
        "boxShadow": "var(--shadow-low)",
        ":hover": {
          "borderColor": "var(--color-accent)",
          "color": "var(--color-text-accent)",
          "boxShadow": "var(--shadow-med)",
          "transform": "translateY(-1px)"
        }
      },
      "variant:ghost": {
        "backgroundColor": "transparent",
        "borderColor": "transparent",
        "color": "var(--color-text-primary)",
        "boxShadow": "none",
        ":hover": {
          "backgroundColor": "var(--color-background-muted)"
        }
      }
    },
    "badge": {
      "variant:info": {
        "backgroundColor": "var(--astryx-theme-neutral-color-status-fill-accent)",
        "color": "var(--color-on-accent)"
      },
      "variant:neutral": {
        "backgroundColor": "var(--color-background-gray)",
        "color": "var(--color-text-gray)"
      },
      "variant:success": {
        "backgroundColor": "var(--astryx-theme-neutral-color-status-fill-success)",
        "color": "var(--color-on-success)"
      },
      "variant:warning": {
        "backgroundColor": "var(--color-warning)",
        "color": "var(--color-on-warning)"
      },
      "variant:error": {
        "backgroundColor": "var(--astryx-theme-neutral-color-status-fill-error)",
        "color": "var(--color-on-error)"
      },
      "variant:red": {
        "backgroundColor": "var(--color-background-red)",
        "color": "var(--color-text-red)"
      },
      "variant:orange": {
        "backgroundColor": "var(--color-background-orange)",
        "color": "var(--color-text-orange)"
      },
      "variant:yellow": {
        "backgroundColor": "var(--color-background-yellow)",
        "color": "var(--color-text-yellow)"
      },
      "variant:green": {
        "backgroundColor": "var(--color-background-green)",
        "color": "var(--color-text-green)"
      },
      "variant:teal": {
        "backgroundColor": "var(--color-background-teal)",
        "color": "var(--color-text-teal)"
      },
      "variant:cyan": {
        "backgroundColor": "var(--color-background-cyan)",
        "color": "var(--color-text-cyan)"
      },
      "variant:blue": {
        "backgroundColor": "var(--color-background-blue)",
        "color": "var(--color-text-blue)"
      },
      "variant:purple": {
        "backgroundColor": "var(--color-background-purple)",
        "color": "var(--color-text-purple)"
      },
      "variant:pink": {
        "backgroundColor": "var(--color-background-pink)",
        "color": "var(--color-text-pink)"
      },
      "variant:gray": {
        "backgroundColor": "var(--color-background-gray)",
        "color": "var(--color-text-gray)"
      },
      "base": {
        "borderColor": "currentColor",
        "borderRadius": "var(--radius-full)",
        "borderStyle": "solid",
        "borderWidth": "1px",
        "fontWeight": "600"
      }
    },
    "statusdot": {
      "variant:success": {
        "backgroundColor": "var(--astryx-theme-neutral-color-status-fill-success)"
      },
      "variant:warning": {
        "backgroundColor": "var(--astryx-theme-neutral-color-status-fill-warning)"
      },
      "variant:error": {
        "backgroundColor": "var(--astryx-theme-neutral-color-status-fill-error)"
      },
      "variant:accent": {
        "backgroundColor": "var(--astryx-theme-neutral-color-status-fill-accent)"
      }
    },
    "avatar-status-dot": {
      "variant:success": {
        "backgroundColor": "var(--astryx-theme-neutral-color-status-fill-success)"
      },
      "variant:error": {
        "backgroundColor": "var(--astryx-theme-neutral-color-status-fill-error)"
      }
    },
    "segmented-control": {
      "base": {
        "padding": "var(--spacing-1)"
      }
    },
    "segmented-control-item": {
      "size:sm": {
        "height": "calc(var(--size-element-sm) - 8px)"
      },
      "size:md": {
        "height": "calc(var(--size-element-md) - 8px)"
      },
      "size:lg": {
        "height": "calc(var(--size-element-lg) - 8px)"
      },
      "selected": {
        "boxShadow": "none"
      }
    },
    "banner": {
      "base": {
        "--color-neutral": "var(--astryx-theme-neutral-color-on-tint-neutral)",
        "--color-overlay-hover": "var(--astryx-theme-neutral-color-on-tint-overlay-hover)",
        "--color-overlay-pressed": "var(--astryx-theme-neutral-color-on-tint-overlay-pressed)"
      },
      "status:info": {
        "--color-accent-muted": "var(--astryx-theme-neutral-color-status-muted-accent)",
        "--color-text-primary": "var(--color-text-blue)",
        "--color-text-secondary": "var(--color-text-blue)",
        "--color-accent": "var(--color-text-blue)"
      },
      "status:success": {
        "--color-text-primary": "var(--color-text-green)",
        "--color-text-secondary": "var(--color-text-green)",
        "--color-success": "var(--color-text-green)"
      },
      "status:warning": {
        "--color-text-primary": "var(--color-text-yellow)",
        "--color-text-secondary": "var(--color-text-yellow)",
        "--color-warning": "var(--color-text-yellow)"
      },
      "status:error": {
        "--color-text-primary": "var(--color-text-red)",
        "--color-text-secondary": "var(--color-text-red)",
        "--color-error": "var(--color-text-red)"
      }
    },
    "step-indicator": {
      "status:accent": {
        "--color-accent": "var(--astryx-theme-neutral-color-status-fill-accent)"
      },
      "status:success": {
        "--color-success": "var(--astryx-theme-neutral-color-status-fill-success)"
      },
      "status:warning": {
        "--color-warning": "var(--astryx-theme-neutral-color-status-fill-warning)"
      },
      "status:error": {
        "--color-error": "var(--astryx-theme-neutral-color-status-fill-error)"
      }
    },
    "switch": {
      "base": {
        "--color-background-gray": "var(--color-border-emphasized)",
        "backgroundColor": "var(--color-background-muted)",
        "borderColor": "var(--color-border-emphasized)",
        "borderWidth": "2px"
      },
      "checked": {
        "backgroundColor": "var(--color-accent)",
        "borderColor": "var(--color-accent)"
      },
      "disabled": {
        "backgroundColor": "var(--color-background-muted)",
        "borderColor": "var(--color-border)"
      }
    },
    "progressbar": {
      "base": {
        "--color-background-muted": "var(--color-border-emphasized)"
      },
      "variant:accent": {
        "--color-accent": "var(--astryx-theme-neutral-color-status-fill-accent)"
      },
      "variant:success": {
        "--color-success": "var(--astryx-theme-neutral-color-status-fill-success)"
      },
      "variant:warning": {
        "--color-warning": "var(--astryx-theme-neutral-color-status-fill-warning)"
      },
      "variant:error": {
        "--color-error": "var(--astryx-theme-neutral-color-status-fill-error)"
      }
    },
    "card": {
      "base": {
        "padding": "24px",
        "borderColor": "var(--color-border)",
        "borderRadius": "var(--radius-container)",
        "borderWidth": "2px",
        "boxShadow": "var(--shadow-low)"
      }
    },
    "section": {
      "base": {
        "padding": "var(--spacing-3)"
      }
    },
    "checkbox-input": {
      "base": {
        "borderRadius": "var(--radius-element)",
        "minHeight": "56px"
      }
    },
    "checkbox-indicator": {
      "base": {
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border-emphasized)",
        "borderRadius": "10px",
        "borderWidth": "2px",
        "boxShadow": "0 2px 0 var(--color-border)",
        "height": "30px",
        "width": "30px"
      },
      "checked": {
        "backgroundColor": "var(--color-accent)",
        "borderColor": "var(--color-accent)",
        "boxShadow": "0 2px 0 var(--color-border-emphasized)",
        "color": "var(--color-on-accent)"
      },
      "disabled": {
        "backgroundColor": "var(--color-background-muted)",
        "borderColor": "var(--color-border)",
        "boxShadow": "none"
      }
    },
    "checkbox-label": {
      "base": {
        "fontWeight": "600"
      }
    },
    "checkbox-list": {
      "base": {
        "borderRadius": "var(--radius-element)"
      }
    },
    "radio-list": {
      "base": {
        "borderRadius": "var(--radius-container)"
      }
    },
    "radio-list-item": {
      "base": {
        "borderColor": "transparent",
        "borderRadius": "var(--radius-element)",
        "borderStyle": "solid",
        "borderWidth": "2px",
        "minHeight": "56px"
      },
      "selected": {
        "backgroundColor": "var(--color-accent-muted)",
        "borderColor": "var(--color-accent)"
      },
      "disabled": {
        "backgroundColor": "var(--color-background-muted)",
        "borderColor": "var(--color-border)"
      }
    },
    "radio-indicator": {
      "base": {
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border-emphasized)",
        "borderWidth": "2px",
        "boxShadow": "0 2px 0 var(--color-border)",
        "height": "30px",
        "width": "30px"
      },
      "checked": {
        "backgroundColor": "var(--color-accent)",
        "borderColor": "var(--color-accent)",
        "boxShadow": "0 2px 0 var(--color-border-emphasized)"
      },
      "disabled": {
        "backgroundColor": "var(--color-background-muted)",
        "borderColor": "var(--color-border)",
        "boxShadow": "none"
      }
    },
    "radio-indicator-dot": {
      "base": {
        "backgroundColor": "var(--color-on-accent)"
      }
    },
    "switch-thumb": {
      "base": {
        "backgroundColor": "var(--color-background-surface)",
        "boxShadow": "0 2px 0 var(--color-border)",
        "borderColor": "var(--color-border-emphasized)",
        "borderWidth": "2px"
      },
      "checked": {
        "backgroundColor": "var(--color-on-accent)",
        "boxShadow": "0 2px 0 var(--color-border-emphasized)"
      }
    },
    "switch-field": {
      "base": {
        "borderRadius": "var(--radius-element)",
        "minHeight": "56px"
      }
    },
    "switch-label": {
      "base": {
        "fontWeight": "600"
      }
    },
    "text-input": {
      "base": {
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border-emphasized)",
        "borderRadius": "var(--radius-full)",
        "borderWidth": "2px",
        "boxShadow": "0 3px 0 var(--color-border)",
        "fontWeight": "500",
        "minHeight": "56px",
        "paddingInline": "24px"
      }
    },
    "selector": {
      "base": {
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border-emphasized)",
        "borderRadius": "var(--radius-full)",
        "borderWidth": "2px",
        "boxShadow": "0 3px 0 var(--color-border)",
        "fontWeight": "500",
        "minHeight": "56px"
      }
    },
    "selector-option": {
      "base": {
        "color": "var(--color-text-primary)"
      }
    },
    "selector-option-row": {
      "base": {
        "borderColor": "transparent",
        "borderRadius": "var(--radius-inner)",
        "borderStyle": "solid",
        "borderWidth": "2px",
        "minHeight": "52px"
      },
      "selected": {
        "backgroundColor": "var(--color-accent-muted)",
        "borderColor": "var(--color-accent)"
      },
      "disabled": {
        "backgroundColor": "var(--color-background-muted)"
      }
    },
    "selector-popup": {
      "base": {
        "backgroundColor": "var(--color-background-popover)",
        "borderColor": "var(--color-border-emphasized)",
        "borderRadius": "var(--radius-container)",
        "borderWidth": "2px",
        "boxShadow": "var(--shadow-med)"
      }
    },
    "selector-section-heading": {
      "base": {
        "color": "var(--color-text-secondary)",
        "fontWeight": "600"
      }
    },
    "selector-empty-state": {
      "base": {
        "color": "var(--color-text-secondary)"
      }
    },
    "tab-list": {
      "base": {
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border)",
        "borderRadius": "var(--radius-container)",
        "borderWidth": "2px",
        "boxShadow": "0 2px 0 var(--color-border)",
        "minHeight": "56px"
      }
    },
    "tab-strip": {
      "base": {
        "gap": "var(--spacing-1)",
        "padding": "var(--spacing-1)"
      }
    },
    "tab": {
      "base": {
        "borderRadius": "var(--radius-full)",
        "color": "var(--color-text-secondary)",
        "fontWeight": "600",
        "minHeight": "48px"
      },
      "selected": {
        "backgroundColor": "var(--color-background-card)",
        "color": "var(--color-text-primary)",
        "boxShadow": "0 2px 0 var(--color-border)"
      }
    },
    "tab-indicator": {
      "selected": {
        "backgroundColor": "var(--color-accent)",
        "borderRadius": "var(--radius-full)"
      }
    },
    "collapsible": {
      "base": {
        "backgroundColor": "var(--color-background-card)",
        "borderColor": "var(--color-border)",
        "borderRadius": "var(--radius-container)",
        "borderWidth": "2px",
        "overflow": "hidden"
      }
    },
    "collapsible-group": {
      "base": {
        "borderRadius": "var(--radius-container)"
      }
    },
    "collapsible-trigger": {
      "base": {
        "backgroundColor": "var(--color-background-card)",
        "color": "var(--color-text-primary)",
        "fontWeight": "700",
        "minHeight": "56px"
      }
    },
    "collapsible-content": {
      "base": {
        "borderTopColor": "var(--color-border)",
        "borderTopStyle": "solid",
        "borderTopWidth": "2px"
      }
    },
    "token": {
      "base": {
        "borderColor": "var(--color-border-emphasized)",
        "borderRadius": "var(--radius-full)",
        "borderStyle": "solid",
        "borderWidth": "2px",
        "fontWeight": "600",
        "minHeight": "44px"
      }
    },
    "tooltip": {
      "base": {
        "backgroundColor": "var(--color-text-primary)",
        "borderColor": "var(--color-accent)",
        "borderRadius": "var(--radius-element)",
        "borderStyle": "solid",
        "borderWidth": "2px",
        "boxShadow": "var(--shadow-med)",
        "color": "var(--color-background-surface)"
      }
    },
    "toast": {
      "base": {
        "backgroundColor": "var(--color-background-popover)",
        "borderColor": "var(--color-accent)",
        "borderRadius": "var(--radius-container)",
        "borderStyle": "solid",
        "borderWidth": "2px",
        "boxShadow": "var(--shadow-high)"
      },
      "type:error": {
        "borderColor": "var(--color-error)"
      }
    },
    "skeleton": {
      "base": {
        "backgroundColor": "var(--color-skeleton)",
        "borderRadius": "var(--radius-inner)"
      }
    },
    "spinner": {
      "base": {
        "--spinner-color": "var(--color-accent)",
        "--spinner-track-color": "var(--color-track)"
      }
    },
    "empty-state": {
      "base": {
        "backgroundColor": "var(--color-background-card)",
        "borderColor": "var(--color-border)",
        "borderRadius": "var(--radius-container)",
        "borderStyle": "solid",
        "borderWidth": "2px",
        "boxShadow": "var(--shadow-low)"
      }
    },
    "empty-state-title": {
      "base": {
        "color": "var(--color-text-primary)",
        "fontWeight": "700"
      }
    },
    "empty-state-description": {
      "base": {
        "color": "var(--color-text-secondary)"
      }
    },
    "field-status": {
      "base": {
        "borderRadius": "var(--radius-element)",
        "borderStyle": "solid",
        "borderWidth": "2px"
      },
      "type:error": {
        "backgroundColor": "var(--color-error-muted)",
        "borderColor": "var(--color-error)",
        "color": "var(--color-text-red)"
      },
      "type:warning": {
        "backgroundColor": "var(--color-warning-muted)",
        "borderColor": "var(--color-warning)",
        "color": "var(--color-text-yellow)"
      },
      "type:success": {
        "backgroundColor": "var(--color-success-muted)",
        "borderColor": "var(--color-success)",
        "color": "var(--color-text-green)"
      }
    },
    "divider": {
      "base": {
        "color": "var(--color-border-emphasized)"
      }
    },
    "dialog": {
      "base": {
        "backgroundColor": "var(--color-background-popover)",
        "borderColor": "var(--color-border-emphasized)",
        "borderRadius": "var(--radius-container)",
        "borderStyle": "solid",
        "borderWidth": "2px",
        "boxShadow": "var(--shadow-high)",
        "padding": "24px"
      }
    },
    "carousel": {
      "base": {
        "backgroundColor": "var(--color-background-card)",
        "borderColor": "var(--color-border)",
        "borderRadius": "var(--radius-container)",
        "borderStyle": "solid",
        "borderWidth": "2px",
        "boxShadow": "0 2px 0 var(--color-border)"
      }
    },
    "carousel-scroller": {
      "base": {
        "scrollPaddingBlock": "var(--spacing-2)"
      }
    },
    "form-layout": {
      "base": {
        "borderRadius": "var(--radius-container)"
      }
    },
    "field": {
      "base": {
        "borderRadius": "var(--radius-element)"
      }
    },
    "field-label": {
      "base": {
        "fontWeight": "600"
      }
    },
    "slider": {
      "base": {
        "color": "var(--color-accent)"
      }
    },
    "slider-track": {
      "base": {
        "backgroundColor": "var(--color-background-muted)",
        "borderColor": "var(--color-border)",
        "borderRadius": "var(--radius-full)",
        "borderStyle": "solid",
        "borderWidth": "2px"
      }
    },
    "slider-thumb": {
      "base": {
        "backgroundColor": "var(--color-accent)",
        "borderColor": "var(--color-accent)",
        "borderStyle": "solid",
        "borderWidth": "2px",
        "boxShadow": "0 2px 0 var(--color-border-emphasized)"
      }
    },
    "date-input": {
      "base": {
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border-emphasized)",
        "borderRadius": "var(--radius-full)",
        "borderWidth": "2px",
        "boxShadow": "0 3px 0 var(--color-border)",
        "fontWeight": "500",
        "minHeight": "56px",
        "paddingInline": "24px"
      }
    },
    "date-input-toggle-icon": {
      "base": {
        "color": "var(--color-icon-accent)"
      }
    },
    "time-input": {
      "base": {
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border-emphasized)",
        "borderRadius": "var(--radius-full)",
        "borderWidth": "2px",
        "boxShadow": "0 3px 0 var(--color-border)",
        "fontWeight": "500",
        "minHeight": "56px",
        "paddingInline": "24px"
      }
    },
    "timestamp": {
      "base": {
        "fontWeight": "600"
      }
    },
    "table": {
      "base": {
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border)",
        "borderRadius": "var(--radius-container)",
        "borderStyle": "solid",
        "borderWidth": "2px",
        "overflow": "hidden"
      }
    },
    "table-header": {
      "base": {
        "backgroundColor": "var(--color-background-muted)"
      }
    },
    "table-header-cell": {
      "base": {
        "color": "var(--color-text-primary)",
        "fontWeight": "700",
        "minHeight": "56px"
      }
    },
    "table-cell": {
      "base": {
        "color": "var(--color-text-primary)",
        "minHeight": "56px"
      }
    },
    "pagination": {
      "base": {
        "borderRadius": "var(--radius-full)",
        "minHeight": "56px"
      }
    },
    "pagination-dot": {
      "base": {
        "backgroundColor": "var(--color-background-muted)",
        "borderColor": "var(--color-border)",
        "borderStyle": "solid",
        "borderWidth": "2px"
      }
    },
    "file-input": {
      "base": {
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border-emphasized)",
        "borderRadius": "var(--radius-container)",
        "borderStyle": "solid",
        "borderWidth": "2px",
        "minHeight": "72px"
      },
      "mode:dropzone": {
        "backgroundColor": "var(--color-background-muted)",
        "borderColor": "var(--color-accent)",
        "borderStyle": "dashed"
      }
    },
    "thumbnail": {
      "base": {
        "backgroundColor": "var(--color-background-muted)",
        "borderColor": "var(--color-border-emphasized)",
        "borderRadius": "var(--radius-element)",
        "borderStyle": "solid",
        "borderWidth": "2px"
      }
    },
    "lightbox": {
      "base": {
        "backgroundColor": "var(--color-overlay)",
        "color": "var(--color-on-dark)"
      }
    },
    "bottom-sheet": {
      "base": {
        "backgroundColor": "var(--color-background-popover)",
        "borderColor": "var(--color-border-emphasized)",
        "borderRadius": "var(--radius-page)",
        "borderStyle": "solid",
        "borderWidth": "2px",
        "boxShadow": "var(--shadow-high)"
      }
    },
    "code": {
      "base": {
        "backgroundColor": "var(--color-background-muted)",
        "borderRadius": "var(--radius-inner)"
      }
    },
    "code-block": {
      "base": {
        "backgroundColor": "var(--color-background-card)",
        "borderColor": "var(--color-border)",
        "borderRadius": "var(--radius-container)",
        "borderStyle": "solid",
        "borderWidth": "2px",
        "boxShadow": "var(--shadow-low)"
      }
    },
    "code-block-header": {
      "base": {
        "backgroundColor": "var(--color-background-muted)"
      }
    },
    "code-block-title": {
      "base": {
        "color": "var(--color-text-primary)",
        "fontWeight": "700"
      }
    },
    "code-block-copy-button": {
      "base": {
        "color": "var(--color-text-accent)"
      }
    },
    "progress-bar-track": {
      "base": {
        "backgroundColor": "var(--color-background-muted)",
        "borderColor": "var(--color-border-emphasized)",
        "borderRadius": "var(--radius-full)",
        "borderStyle": "solid",
        "borderWidth": "2px",
        "boxSizing": "border-box",
        "height": "16px"
      }
    },
    "progress-bar-fill": {
      "variant:accent": {
        "backgroundColor": "var(--color-accent)"
      },
      "variant:success": {
        "backgroundColor": "var(--color-success)"
      },
      "variant:warning": {
        "backgroundColor": "var(--color-warning)"
      },
      "variant:error": {
        "backgroundColor": "var(--color-error)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  __adaptations: {
    "widthBreakpoints": {
      "sm": 640,
      "md": 768,
      "lg": 1024,
      "xl": 1280,
      "2xl": 1536
    },
    "rules": []
  },
  __axes: {
    "typography": {
      "scale": {
        "base": 20,
        "ratio": 1.24
      },
      "body": {
        "family": "Nunito Variable",
        "fallbacks": "Nunito Variable, \"Noto Sans SC Variable\", \"PingFang SC\", \"Hiragino Sans GB\", \"Microsoft YaHei\", sans-serif",
        "weight": "medium"
      },
      "heading": {
        "family": "Nunito Variable",
        "fallbacks": "Nunito Variable, \"Noto Sans SC Variable\", \"PingFang SC\", \"Hiragino Sans GB\", \"Microsoft YaHei\", sans-serif",
        "weight": "bold"
      },
      "code": {
        "family": "ui-monospace",
        "fallbacks": "\"SF Mono\", Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace"
      }
    },
    "color": {
      "accent": [
        "#1F7A68",
        "#7BE0C1"
      ],
      "neutralStyle": "warm",
      "contrast": "standard"
    },
    "motion": {
      "fast": 200,
      "medium": 340,
      "slow": 620,
      "ratio": 0.8
    }
  },

};
