/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/components/appearance/themes/kids-sprout.ts
 * Command: astryx theme build src/components/appearance/themes/kids-sprout.ts
 * CLI: @astryxdesign/cli@0.6.0
 * Core: @astryxdesign/core@0.6.0
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
