/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/components/appearance/themes/kids-sprout.ts
 * Command: astryx theme build src/components/appearance/themes/kids-sprout.ts
 * CLI: @astryxdesign/cli@0.6.0
 * Core: @astryxdesign/core@0.6.0
 */

/// <reference path="./kids-sprout.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const kidsSproutTheme: DefinedTheme;
