#!/usr/bin/env node
/**
 * openspec-docs-sync
 * Idempotent sync engine: openspec/changes/archive → apps/docs/content/docs/changelog
 *                          roadmap.yaml             → apps/docs/content/docs/roadmap/index.mdx
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import matter from 'gray-matter'
import yaml from 'js-yaml'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// Resolve workspace root (two levels up from packages/openspec-docs-sync/src)
const WORKSPACE_ROOT = path.resolve(__dirname, '..', '..', '..')

const ARCHIVE_DIR = path.join(WORKSPACE_ROOT, 'openspec', 'changes', 'archive')
const ROADMAP_FILE = path.join(WORKSPACE_ROOT, 'roadmap.yaml')
const CHANGELOG_OUT_DIR = path.join(
  WORKSPACE_ROOT,
  'apps',
  'docs',
  'content',
  'docs',
  'changelog',
)
const ROADMAP_OUT_DIR = path.join(
  WORKSPACE_ROOT,
  'apps',
  'docs',
  'content',
  'docs',
  'roadmap',
)

const AUTO_GENERATED_HEADER =
  '<!-- AUTO-GENERATED by openspec-docs-sync. Do not edit manually. -->'

// ── Types ────────────────────────────────────────────────────────────────────

interface ArchivedChange {
  /** Directory name e.g. "2026-06-01-bootstrap-platform-skeleton" */
  dirName: string
  /** Parsed date from directory prefix */
  date: string
  /** Change id (part after YYYY-MM-DD-) */
  id: string
  /** roadmap-id from frontmatter, if present */
  roadmapId: string | null
  why: string
  capabilities: string
  nonGoals: string
  title: string
}

interface RoadmapEntry {
  id: string
  title: string
  status: string
  owner: string
}

interface RoadmapData {
  now: RoadmapEntry[]
  next: RoadmapEntry[]
  later: RoadmapEntry[]
  wont: RoadmapEntry[]
}

// ── Parsing ──────────────────────────────────────────────────────────────────

/**
 * Extract a Markdown section by heading. Returns the content between this
 * heading and the next same-level heading (or end of file).
 */
function extractSection(content: string, heading: string): string {
  const lines = content.split('\n')
  const level = heading.match(/^(#{1,6})/)?.[1]?.length ?? 2
  const headingPattern = new RegExp(`^#{${level}}\\s+${escapeRegex(heading.replace(/^#+\s*/, ''))}`)
  let inSection = false
  const sectionLines: string[] = []

  for (const line of lines) {
    if (inSection) {
      const isNewSection = new RegExp(`^#{1,${level}}\\s`).test(line)
      if (isNewSection) break
      sectionLines.push(line)
    } else if (headingPattern.test(line)) {
      inSection = true
    }
  }

  return sectionLines.join('\n').trim()
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

/**
 * Derive a human-friendly title from the change id.
 * e.g. "bootstrap-platform-skeleton" → "Bootstrap Platform Skeleton"
 */
function idToTitle(id: string): string {
  return id
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}

function parseArchivedChange(dirName: string): ArchivedChange | null {
  // Expect format: YYYY-MM-DD-<id>
  const match = dirName.match(/^(\d{4}-\d{2}-\d{2})-(.+)$/)
  if (!match) return null

  const date = match[1] as string
  const id = match[2] as string

  const proposalPath = path.join(ARCHIVE_DIR, dirName, 'proposal.md')
  if (!fs.existsSync(proposalPath)) return null

  const raw = fs.readFileSync(proposalPath, 'utf-8')
  const parsed = matter(raw)
  const content = parsed.content

  const roadmapId = (parsed.data['roadmap-id'] as string | undefined) ?? null
  const why = extractSection(content, '## Why')
  const capabilities = extractSection(content, '## Capabilities')
  const nonGoals = extractSection(content, '## Non-goals')
  const title = idToTitle(id)

  return { dirName, date, id, roadmapId, why, capabilities, nonGoals, title }
}

// ── Changelog generation ─────────────────────────────────────────────────────

function generateChangelogMdx(change: ArchivedChange): string {
  const description = `Archived on ${change.date}${change.roadmapId ? ` · roadmap: ${change.roadmapId}` : ''}`

  const sections: string[] = []

  if (change.why) {
    sections.push(`## Why\n\n${change.why}`)
  }
  if (change.capabilities) {
    sections.push(`## Capabilities\n\n${change.capabilities}`)
  }
  if (change.nonGoals) {
    sections.push(`## Non-goals\n\n${change.nonGoals}`)
  }

  return [
    '---',
    `title: "${change.title}"`,
    `description: "${description}"`,
    '---',
    '',
    `{/* ${AUTO_GENERATED_HEADER} */}`,
    '',
    `> Archived: ${change.date}${change.roadmapId ? `  ·  roadmap-id: \`${change.roadmapId}\`` : ''}`,
    '',
    ...sections,
  ].join('\n')
}

function syncChangelog(changes: ArchivedChange[]): void {
  fs.mkdirSync(CHANGELOG_OUT_DIR, { recursive: true })

  // Sort by date descending (newest first)
  const sorted = [...changes].sort((a, b) => b.date.localeCompare(a.date))

  for (const change of sorted) {
    const outPath = path.join(CHANGELOG_OUT_DIR, `${change.id}.mdx`)
    const mdx = generateChangelogMdx(change)
    fs.writeFileSync(outPath, mdx, 'utf-8')
    console.log(`  ✓ changelog/${change.id}.mdx`)
  }

  // Generate index page listing all changes
  const indexContent = generateChangelogIndex(sorted)
  fs.writeFileSync(path.join(CHANGELOG_OUT_DIR, 'index.mdx'), indexContent, 'utf-8')
  console.log(`  ✓ changelog/index.mdx`)
}

function generateChangelogIndex(changes: ArchivedChange[]): string {
  const items = changes
    .map((c) => `- [${c.title}](./${c.id}) — archived ${c.date}`)
    .join('\n')

  return [
    '---',
    'title: "Changelog"',
    'description: "Archived changes and decision log, newest first."',
    '---',
    '',
    `{/* ${AUTO_GENERATED_HEADER} */}`,
    '',
    'Archived changes in reverse-chronological order.',
    '',
    items,
  ].join('\n')
}

// ── Roadmap generation ────────────────────────────────────────────────────────

function statusBadge(status: string): string {
  const map: Record<string, string> = {
    done: '✅',
    'in-progress': '🔄',
    planned: '📋',
  }
  return map[status] ?? status
}

function renderBucket(entries: RoadmapEntry[]): string {
  if (!entries || entries.length === 0) return '_No items._'
  return entries
    .map(
      (e) =>
        `- ${statusBadge(e.status)} **${e.title}** \`${e.id}\`  \n  Status: ${e.status} · Owner: ${e.owner}`,
    )
    .join('\n')
}

function generateRoadmapMdx(data: RoadmapData): string {
  return [
    '---',
    'title: "Roadmap"',
    'description: "Current platform roadmap — four-bucket view (Now / Next / Later / Won\'t)."',
    '---',
    '',
    `{/* ${AUTO_GENERATED_HEADER} */}`,
    '',
    '> Auto-generated from `roadmap.yaml`. To update, edit the YAML and re-run `pnpm docs:sync`.',
    '',
    '## Now',
    '',
    renderBucket(data.now),
    '',
    '## Next',
    '',
    renderBucket(data.next),
    '',
    '## Later',
    '',
    renderBucket(data.later),
    '',
    "## Won't",
    '',
    renderBucket(data.wont),
  ].join('\n')
}

function syncRoadmap(): void {
  fs.mkdirSync(ROADMAP_OUT_DIR, { recursive: true })

  const raw = fs.readFileSync(ROADMAP_FILE, 'utf-8')
  const data = yaml.load(raw) as RoadmapData

  const mdx = generateRoadmapMdx(data)
  const outPath = path.join(ROADMAP_OUT_DIR, 'index.mdx')
  fs.writeFileSync(outPath, mdx, 'utf-8')
  console.log(`  ✓ roadmap/index.mdx`)
}

// ── Entry point ───────────────────────────────────────────────────────────────

function main(): void {
  console.log('openspec-docs-sync: starting…')
  console.log(`  workspace: ${WORKSPACE_ROOT}`)

  // 1. Scan archive
  if (!fs.existsSync(ARCHIVE_DIR)) {
    console.error(`  ✗ Archive directory not found: ${ARCHIVE_DIR}`)
    process.exit(1)
  }

  const archiveDirs = fs.readdirSync(ARCHIVE_DIR).filter((d) => {
    const full = path.join(ARCHIVE_DIR, d)
    return fs.statSync(full).isDirectory()
  })

  console.log(`  Found ${archiveDirs.length} archived change(s).`)

  const changes: ArchivedChange[] = []
  for (const dirName of archiveDirs) {
    const change = parseArchivedChange(dirName)
    if (change) {
      changes.push(change)
    } else {
      console.warn(`  ⚠ Skipping unrecognised archive dir: ${dirName}`)
    }
  }

  // 2. Sync changelog MDX files (idempotent: overwrites by id)
  console.log('\n  Syncing changelog…')
  syncChangelog(changes)

  // 3. Sync roadmap MDX
  console.log('\n  Syncing roadmap…')
  syncRoadmap()

  console.log('\nopenspec-docs-sync: done ✓')
}

main()
