#!/bin/bash

# End-to-End Template Test Script
# Creates a real project from template, tests it, then cleans up
# Usage: ./scripts/e2e-template-test.sh

set -e

# ==========================================
# Configuration
# ==========================================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TEMPLATE_DIR="$ROOT_DIR/templates/web-nextjs/apps/web"
TEST_PROJECTS_DIR="$ROOT_DIR/test-projects"
TEST_PROJECT_NAME="test-web-nextjs-$(date +%s)"
TEST_PROJECT_PATH="$TEST_PROJECTS_DIR/$TEST_PROJECT_NAME"

COLOR_RESET='\033[0m'
COLOR_GREEN='\033[0;32m'
COLOR_RED='\033[0;31m'
COLOR_YELLOW='\033[1;33m'
COLOR_BLUE='\033[0;34m'
COLOR_CYAN='\033[0;36m'

echo -e "${COLOR_CYAN}╔════════════════════════════════════════════════════════╗${COLOR_RESET}"
echo -e "${COLOR_CYAN}║  End-to-End Template Test                             ║${COLOR_RESET}"
echo -e "${COLOR_CYAN}║  $(date)${COLOR_RESET}"
echo -e "${COLOR_CYAN}╚════════════════════════════════════════════════════════╝${COLOR_RESET}"
echo ""

PASS_COUNT=0
FAIL_COUNT=0
WARN_COUNT=0

pass() {
    echo -e "${COLOR_GREEN}✓ PASS${COLOR_RESET}: $1"
    PASS_COUNT=$((PASS_COUNT + 1))
}

fail() {
    echo -e "${COLOR_RED}✗ FAIL${COLOR_RESET}: $1"
    FAIL_COUNT=$((FAIL_COUNT + 1))
}

warn() {
    echo -e "${COLOR_YELLOW}⚠ WARN${COLOR_RESET}: $1"
    WARN_COUNT=$((WARN_COUNT + 1))
}

section() {
    echo ""
    echo -e "${COLOR_BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${COLOR_RESET}"
    echo -e "${COLOR_BLUE}  $1${COLOR_RESET}"
    echo -e "${COLOR_BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${COLOR_RESET}"
}

cleanup() {
    echo ""
    section "Cleanup"

    if [ -d "$TEST_PROJECT_PATH" ]; then
        echo "Removing test project: $TEST_PROJECT_PATH"
        rm -rf "$TEST_PROJECT_PATH"
        pass "Test project removed"
    else
        warn "Test project directory not found (already cleaned up?)"
    fi

    # Kill any running dev servers on port 3000
    if lsof -ti:3000 > /dev/null 2>&1; then
        echo "Killing processes on port 3000..."
        lsof -ti:3000 | xargs kill -9 2>/dev/null || true
        pass "Dev server stopped"
    fi
}

# Trap to ensure cleanup on exit
trap cleanup EXIT INT TERM

# ==========================================
# Pre-flight Checks
# ==========================================
section "Pre-flight Checks"

if [ ! -f "$ROOT_DIR/.env.local" ]; then
    fail "Root .env.local not found at $ROOT_DIR/.env.local"
    echo "Please create it with required environment variables."
    exit 1
else
    pass "Root .env.local exists"
fi

if [ ! -d "$TEMPLATE_DIR" ]; then
    fail "Template directory not found: $TEMPLATE_DIR"
    exit 1
else
    pass "Template directory exists"
fi

if command -v pnpm &> /dev/null; then
    pass "pnpm available"
else
    fail "pnpm not found"
    exit 1
fi

# ==========================================
# Step 1: Create Test Project from Template
# ==========================================
section "Step 1: Creating Test Project from Template"

mkdir -p "$TEST_PROJECTS_DIR"

echo "Copying template to: $TEST_PROJECT_PATH"
cp -r "$TEMPLATE_DIR" "$TEST_PROJECT_PATH"

if [ -d "$TEST_PROJECT_PATH" ]; then
    pass "Test project created"
    echo "  Location: $TEST_PROJECT_PATH"
else
    fail "Failed to create test project"
    exit 1
fi

# ==========================================
# Step 2: Configure Environment Variables
# ==========================================
section "Step 2: Configuring Environment Variables"

cd "$TEST_PROJECT_PATH"

# Extract web-nextjs specific variables from root .env.local
echo "Extracting environment variables from root .env.local..."

# Create .env.local for test project
cat > .env.local << 'EOF'
# Auto-generated by e2e-template-test.sh
# Source: ../../.env.local
EOF

# Copy relevant variables (Supabase and App config)
grep -E "^(NEXT_PUBLIC_SUPABASE_|SUPABASE_SERVICE_ROLE|NEXT_PUBLIC_APP_URL|APP_DEFAULT_LOCALE)" \
    "$ROOT_DIR/.env.local" >> .env.local 2>/dev/null || true

if [ -f ".env.local" ] && grep -q "NEXT_PUBLIC_SUPABASE_URL" .env.local; then
    pass "Environment variables configured"
    echo "  Variables set:"
    grep -E "^(NEXT_PUBLIC_|APP_)" .env.local | sed 's/^/    /'
else
    fail "Failed to configure environment variables"
    cat .env.local
    exit 1
fi

# ==========================================
# Step 3: Install Dependencies
# ==========================================
section "Step 3: Installing Dependencies"

echo "Running pnpm install..."
if pnpm install --frozen-lockfile 2>&1 | tail -20; then
    pass "Dependencies installed successfully"
else
    warn "Frozen lockfile failed, trying regular install..."
    if pnpm install 2>&1 | tail -20; then
        pass "Dependencies installed (non-frozen)"
    else
        fail "Dependency installation failed"
        exit 1
    fi
fi

# ==========================================
# Step 4: Run Automated Checks
# ==========================================
section "Step 4: Running Automated Checks"

# Lint
echo "Running ESLint..."
if pnpm lint 2>&1 | tail -5; then
    pass "ESLint passed"
else
    fail "ESLint failed"
fi

# Type check
echo "Running TypeScript check..."
if pnpm check-types 2>&1 | tail -5; then
    pass "TypeScript compilation successful"
else
    fail "TypeScript errors found"
fi

# Build
echo "Running production build..."
if pnpm build 2>&1 | tail -10; then
    pass "Production build successful"
else
    fail "Production build failed"
    exit 1
fi

# ==========================================
# Step 5: Start Dev Server & Test
# ==========================================
section "Step 5: Starting Dev Server & Testing"

echo "Starting dev server in background..."
pnpm dev > /tmp/test-dev-server.log 2>&1 &
DEV_SERVER_PID=$!

echo "Dev server PID: $DEV_SERVER_PID"
echo "Waiting for server to be ready..."

# Wait for server to be ready (max 60 seconds)
MAX_WAIT=60
WAITED=0
SERVER_READY=false

while [ $WAITED -lt $MAX_WAIT ]; do
    if curl -s http://localhost:3000 > /dev/null 2>&1; then
        SERVER_READY=true
        break
    fi
    sleep 2
    WAITED=$((WAITED + 2))
    echo "  Waiting... ($WAITED/$MAX_WAIT seconds)"
done

if [ "$SERVER_READY" = true ]; then
    pass "Dev server started successfully (${WAITED}s)"
else
    fail "Dev server failed to start within ${MAX_WAIT}s"
    echo "Server logs:"
    cat /tmp/test-dev-server.log | tail -30
    exit 1
fi

# ==========================================
# Step 6: Functional Tests
# ==========================================
section "Step 6: Running Functional Tests"

# Test 1: Homepage loads
echo "Testing homepage..."
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/en)
if [ "$HTTP_CODE" = "200" ]; then
    pass "Homepage returns 200"
else
    fail "Homepage returned $HTTP_CODE (expected 200)"
fi

# Test 2: Login page accessible
echo "Testing login page..."
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/en/login)
if [ "$HTTP_CODE" = "200" ]; then
    pass "Login page accessible"
else
    fail "Login page returned $HTTP_CODE"
fi

# Test 3: Forgot password page exists (NEW FEATURE)
echo "Testing forgot password page..."
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/en/forgot-password)
if [ "$HTTP_CODE" = "200" ]; then
    pass "Forgot password page accessible (NEW FEATURE ✓)"
else
    fail "Forgot password page returned $HTTP_CODE"
fi

# Test 4: Reset password page exists (NEW FEATURE)
echo "Testing reset password page..."
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/en/reset-password)
if [ "$HTTP_CODE" = "200" ]; then
    pass "Reset password page accessible (NEW FEATURE ✓)"
else
    fail "Reset password page returned $HTTP_CODE"
fi

# Test 5: Profile settings page exists (NEW FEATURE)
echo "Testing profile settings page..."
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/en/settings/profile)
if [ "$HTTP_CODE" = "200" ]; then
    pass "Profile settings page accessible (NEW FEATURE ✓)"
else
    fail "Profile settings page returned $HTTP_CODE"
fi

# Test 6: Help page (static placeholder)
echo "Testing help page..."
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/en/help)
if [ "$HTTP_CODE" = "200" ]; then
    pass "Help page accessible"
else
    fail "Help page returned $HTTP_CODE"
fi

# Test 7: Check page content for new features
echo "Checking page content..."
HOMEPAGE_CONTENT=$(curl -s http://localhost:3000/en)
if echo "$HOMEPAGE_CONTENT" | grep -q "Dashboard\|Sign In"; then
    pass "Homepage contains expected content"
else
    warn "Homepage content may have changed (manual review recommended)"
fi

# Test 8: Verify no console errors in server logs
echo "Checking server logs for errors..."
if grep -i "error\|exception" /tmp/test-dev-server.log | grep -v "eslint" | grep -v "warning" > /dev/null; then
    warn "Found potential errors in server logs:"
    grep -i "error\|exception" /tmp/test-dev-server.log | head -5 | sed 's/^/    /'
else
    pass "No critical errors in server logs"
fi

# ==========================================
# Step 7: Security & Architecture Verification
# ==========================================
section "Step 7: Security & Architecture Verification"

# Verify Layer 2 constraint in actual running code
echo "Verifying Layer 2 architecture in built code..."
if grep -r "from '@/infra/db/client'" src/features/*/actions.ts 2>/dev/null; then
    fail "Layer 2 violation found in actions.ts"
else
    pass "No Layer 2 violations in features layer"
fi

# Verify open redirect protection exists
echo "Checking open redirect protection..."
if [ -f "src/app/auth/callback/route.ts" ] && grep -q "ALLOWED_NEXT" src/app/auth/callback/route.ts; then
    pass "Open redirect protection present"
else
    fail "Open redirect protection missing"
fi

# Verify no hardcoded secrets in built output
echo "Scanning for hardcoded secrets..."
if grep -rE "sb-[a-z0-9]{20,}" .next/server/ 2>/dev/null | grep -v ".map" > /dev/null; then
    fail "Potential hardcoded secrets found in build output"
else
    pass "No hardcoded secrets in build output"
fi

# ==========================================
# Summary
# ==========================================
section "Test Summary"

echo -e "${COLOR_CYAN}Test Results:${COLOR_RESET}"
echo -e "  ${COLOR_GREEN}Passed:${COLOR_RESET}   $PASS_COUNT"
echo -e "  ${COLOR_RED}Failed:${COLOR_RESET}   $FAIL_COUNT"
echo -e "  ${COLOR_YELLOW}Warnings:${COLOR_RESET} $WARN_COUNT"
echo ""

if [ $FAIL_COUNT -eq 0 ]; then
    echo -e "${COLOR_GREEN}╔════════════════════════════════════════════════════════╗${COLOR_RESET}"
    echo -e "${COLOR_GREEN}║  ✓ ALL TESTS PASSED!                                  ║${COLOR_RESET}"
    echo -e "${COLOR_GREEN}╚════════════════════════════════════════════════════════╝${COLOR_RESET}"
    echo ""
    echo -e "${COLOR_CYAN}Next Steps:${COLOR_RESET}"
    echo ""
    echo -e "1. ${COLOR_GREEN}✓${COLOR_RESET} Template is ready for merge"
    echo -e "2. ${COLOR_BLUE}→${COLOR_RESET} Merge feature branch to main:"
    echo -e "     git checkout main"
    echo -e "     git merge add-user-account-features"
    echo -e "     git push origin main"
    echo ""
    echo -e "3. ${COLOR_BLUE}→${COLOR_RESET} Update documentation:"
    echo -e "     - apps/docs/content/docs/changelog/index.mdx"
    echo -e "     - apps/docs/content/docs/roadmap/index.mdx"
    echo ""
    echo -e "4. ${COLOR_BLUE}→${COLOR_RESET} Trigger CI/CD pipeline:"
    echo -e "     git tag v0.x.0  # or use GitHub Releases"
    echo -e "     git push origin v0.x.0"
    echo ""
    echo -e "5. ${COLOR_BLUE}→${COLOR_RESET} Final production verification:"
    echo -e "     agentdock create my-app --template web-nextjs"
    echo -e "     cd my-app"
    echo -e "     pnpm install && pnpm dev"
    echo ""
    echo -e "6. ${COLOR_BLUE}→${COLOR_RESET} Cleanup (automatic):"
    echo -e "     Test project will be removed automatically"
    echo ""
else
    echo -e "${COLOR_RED}╔════════════════════════════════════════════════════════╗${COLOR_RESET}"
    echo -e "${COLOR_RED}║  ✗ TESTS FAILED - DO NOT MERGE                        ║${COLOR_RESET}"
    echo -e "${COLOR_RED}╚════════════════════════════════════════════════════════╝${COLOR_RESET}"
    echo ""
    echo -e "${COLOR_RED}Please fix the failures above before proceeding.${COLOR_RESET}"
    echo ""
    echo -e "${COLOR_CYAN}Debugging Tips:${COLOR_RESET}"
    echo -e "  - Check server logs: cat /tmp/test-dev-server.log"
    echo -e "  - Test project location: $TEST_PROJECT_PATH"
    echo -e "  - Re-run this script after fixes"
fi

echo ""
echo -e "${COLOR_CYAN}Test project will be cleaned up automatically...${COLOR_RESET}"

# Exit with appropriate code
if [ $FAIL_COUNT -eq 0 ]; then
    exit 0
else
    exit 1
fi
